name: conda-work-tests
channels:
 - conda-forge

dependencies:
  - python=3.7.3
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - bokeh
  - xlrd
  - sqlalchemy
  - sqlalchemy-utils
  - psycopg2
  - postgresql
  - pyarrow
  - pluggy
  - flask
  - flask-restplus
  - werkzeug=0.16.1